trigger:
  paths:
    include:
      - templatespecs/certifiedfunction

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'deployment-variables'
  - name: bicepPath
    value: "$(Build.Repository.LocalPath)/templatespecs/certifiedfunction"
  - name: fileName
    value: "certifiedfunction"
  - name: specName
    value: "az-tempspec-certifiedfunction"

extends:
  template: templates/stages-specs.yml
  parameters:
    bicepPath: '$(bicepPath)'
    fileName: '$(fileName)'
    serviceConnection: '$(serviceconnection)'
    specName: '$(specName)'
    resourceGroup: '$(resourceGroup)'
    subscription: '$(subscriptionId)'