resources:
 pipelines:
  - pipeline: 'solution-build'
    source: 'BR - Build - Bicep Registry'
    trigger: true

trigger: none

variables:
- group: 'deployment-variables'

stages:
  - stage: Deploy_IaC_Registry
    displayName: Deploy Certified Function
    jobs:
      - deployment: Deployment_Modules
        displayName: Deploy Azure Certified Function
        environment: "Azure Function"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  clean: true
                - script: bicep build-params 'templatespecs/certifiedfunction/certifiedfunction-param.bicepparam'
                  displayName: Convert Bicep Params file
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Infrastructure - Deploy'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '$(serviceconnection-sub)'
                    subscriptionId: '$(subscriptionId)'
                    resourceGroupName: 'sponsor-rg-testing'
                    location: 'West Europe'
                    templateLocation: 'templatespecs/certifiedfunction/certifiedfunction.bicep'
                    csmFile: 'templatespecs/certifiedfunction/certifiedfunction.bicep'
                    csmParametersFile: 'templatespec/certifiedfunction/certifiedfunction-param.json'
                    deploymentMode: 'Incremental'