trigger: none

variables:
- group: 'deployment-variables'

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: Deploy
      displayName: Deploy Certified Function
      continueOnError: false
      steps:
        - task: AzureCLI@2
          displayName: 'Build Bicep file'
          inputs:
            azureSubscription: '$(serviceconnection-sub)'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              cd $(System.DefaultWorkingDirectory)/templatespecs/certifiedfunction
              bicep build '$(System.DefaultWorkingDirectory)/templatespecs/certifiedfunction/certifiedfunction.bicep'
              bicep build-params '$(System.DefaultWorkingDirectory)/templatespecs/certifiedfunction/certifiedfunction-param.bicepparam'
              ls
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Infrastructure - Deploy'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(serviceconnection-sub)'
            subscriptionId: '$(subscription-sub)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'sponsor-rg-testing'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(System.DefaultWorkingDirectory)/templatespecs/certifiedfunction/certifiedfunction.json'
            csmParametersFile: '$(System.DefaultWorkingDirectory)/templatespecs/certifiedfunction/certifiedfunction-param.json'
            deploymentMode: 'Incremental'