name: "Deploy Template Spec"
description: "Composite actions for deploying a template spec."
inputs:
  azureSubscription:
    description: 'Subscription'
    required: true
  specFolder:
    description: 'Specification folder'
    required: true
  specName:
    description: 'Specification name'
    required: true
  resourceGroup:
    description: 'Name of the resource group'
    required: true
  specFileName:
    description: 'The files name of the spec'
    required: true
runs:
  using: "composite"
  steps:
       - uses: actions/download-artifact@v4
         name: Download template spec
         with:
             name: ${{inputs.specName}}
       - uses: actions/download-artifact@v4
         name: Download utility scripts
         with:
             name: ps-${{inputs.specName}}
       - name: Azure login
         uses: azure/login@v2
         with:
          client-id: ${{ secrets.ID_CLIENT_ID }}
          tenant-id: ${{ secrets.ID_TENANT_ID }}
          subscription-id: ${{ secrets.ID_SUBSCRIPTION_ID }}
         enable-AzPSSession: true
       - name: Check versionnumber
         uses: azure/powershell@v1
         id: calculate
         with:
           inlineScript: |
              .\Get-TemplateSpecVersion.ps1 -TemplateSpecName "${{env.specName}}" -ResourceGroupName "${{inputs.resourceGroup}}"
           azPSVersion: '10.2.0'
       - name: Create / Update template spec
         uses: azure/powershell@v1
         with:
           inlineScript: |
            New-AzTemplateSpec -Name "${{inputs.specName}}" -Version "${{ steps.calculate.outputs.versionnumber }}" -ResourceGroupName "${{inputs.resourceGroup}}" -Location "westeurope" -TemplateFile ".\${{inputs.specFileName}}"
           azPSVersion: '10.2.0'