name: Bicep Linting

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        shell: pwsh
        run: |
          $files = git diff HEAD~1 --name-only | Where-Object { $_ -like '*.bicep' -or $_ -like '*.bicepparam' }
          $array = @()
          foreach($file in $files){
            $array += $file
          }
          $items = ConvertTo-Json $array -Compress
          Write-Host $items
          "BICEP_FILES='$items'" >> $env:GITHUB_ENV
      - name: "Linting the bicep files"
        shell: pwsh
        run: |
          $files = ConvertFrom-Json ${{ env.BICEP_FILES }}
          $report = @()
          $report += "## Bicep Linting Report :rocket:"
          if($files.Count -eq 0){
          }else{
            foreach($file in $files){
              $sarif = bicep lint $file --diagnostics-format sarif | ConvertFrom-Json

              foreach ($run in $sarif.runs) {
                    $report += "**$($file)**"
                    foreach ($result in $run.results) {
                      if($result.level -eq "error"){
                        $level = ":triangular_flag_on_post:"
                      }elseif($result.level -eq "warning"){
                        $level = ":warning:"
                      }

                      foreach ($location in $result.locations) {
                          $report != "* $($level) - **Line:** $($location.physicalLocation.region.startLine) - $($result.message.text)"
                        }
                    }
                }
            }
          }
          $report >> $env:GITHUB_STEP_SUMMARY