name: Bicep Linting

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Bicep CLI
        shell: pwsh
        run: |
          az bicep install
      - name: Get changed files
        shell: pwsh
        run: |
          $files = git diff HEAD~1 --name-only | Where-Object { $_ -like '*.bicep' -or $_ -like '*.bicepparam' }
          $array = @()
          foreach($file in $files){
            $array += $file
          }
          $items = ConvertTo-Json $array -Compress
          Write-Host $items
          "BICEP_FILES='$items'" >> $env:GITHUB_ENV
      - name: "Changes"
        shell: pwsh
        run: |
          $files = ConvertFrom-Json ${{ env.BICEP_FILES }}
          $report = @()
          $report += "Bicep Lint Report:"
          if($files.Count -eq 0){
            $report += "No bicep files found in the changes."
          }else{
            foreach($file in $files){
              $lintResult = bicep lint $file --diagnostics-format sarif | ConvertFrom-Json
              Write-Host $lintResult
              if ($lintResult -ne "") {
                foreach ($run in $lintResult.runs) {
                    $report += "### $file"
                    foreach ($result in $run.results) {
                        $message = $result.message.text
                        $level = $result.level

                        if($level -eq "error") {
                            $hasErrors = $true
                        }
                        foreach ($location in $result.locations) {
                            $lineNumber = $location.physicalLocation.region.startLine
                        }
                        $report += "$($level) - $($message) - Line: $($lineNumber)"
                    }
                }
              }
            }
          }
          $report >> $env:GITHUB_STEP_SUMMARY
