# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        shell: pwsh
        run: |
          $files = git diff HEAD~1 --name-only
          $array = @()
          foreach($file in $files){
            $array += $file
          }

          Write-Host $array
          "VAR=$array" >> $env:GITHUB_ENV
      - name: "Changes"
        shell: pwsh
        run: |
          $files = ${{ env.VAR }}
          $report = @()
          $report += 'The following files are changed or added in the last commit:'
          foreach($file in $files){
            $report += '* $file'
          }
          $report >> $env:GITHUB_STEP_SUMMARY
