name: Bicep Linting

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: maikvandergaag/action-biceplint@main
        with:
          allfiles: true
          create-sarif: true
          markdown-report: false
          sarif-output-path: bicep-lint.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bicep-lint.sarif
          category: bicep-linting