name: TS - Certified Storage

on:
  push:
    paths:
      - 'templatespecs/certifiedstorage/*'
      - .github/workflows/*
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  specName: az-tempspec-certifiedstorage-actions
  specfolder: './templatespecs/certifiedstorage/certifiedstorage'
  specfilename: certifiedstorage.json
  resourcegroup: gaag-rg-iac-prd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: bicepbuild
        uses: ./.github/actions/buildbicep
        with:
          specFolder: ${{env.specfolder}}
          specName: ${{env.specName}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - id: deployspec
         uses: ./.github/actions/deploytemplatespec
         with:
           specFolder: ${{env.specfolder}}
           specName: ${{env.specName}}
           resourceGroup: ${{env.resourcegroup}}
           specFileName : ${{env.specfilename}}
           clientId: ${{ secrets.ID_CLIENT_ID }}
           tenantId: ${{ secrets.ID_TENANT_ID }}
           azureSubscription: ${{ secrets.ID_SUBSCRIPTION_ID }}